package com.ac.mavenmybyciclerides;
// Generated 20-Apr-2020 13:17:02 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Rides generated by hbm2java
 */
@Entity
public class Rides  implements java.io.Serializable {

@Id
     private int id;
     private float km;
     private float time;
     private String link;
     private String data;

    public Rides() {
    }

	
    public Rides(int id, float km, float time) {
        this.id = id;
        this.km = km;
        this.time = time;
    }
    public Rides(int id, float km, float time, String link, String data) {
       this.id = id;
       this.km = km;
       this.time = time;
       this.link = link;
       this.data = data;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public float getKm() {
        return this.km;
    }
    
    public void setKm(float km) {
        this.km = km;
    }
    public float getTime() {
        return this.time;
    }
    
    public void setTime(float time) {
        this.time = time;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }




}


